### ISSUE TITLE
CUDA out of memory: distributed training is needed

### ISSUE THREAD

**Issue by ZouJoelin** [ahnjaewoo/MPCHAT#2]
Hello again, I ran into "CUDA out of memory" error now. And I noticed that the distributed training has not been implemented. How can I implement that, could you give me a hint?

**Comment by ahnjaewoo** [comment]
Hi,
We didn't implement distributed training as our model size is relatively small.

Could you please provide more details about (1) your GPU and (2) the phase during which you encountered the Out Of Memory (OOM) error?

(1) For reference, we have successfully trained our clip-clip model on a single Quadro RTX 6000 GPU (24GB) as well as a single TITAN Xp (12GB).

(2) If it occurred during the training phase, you may consider reducing the `args.per_gpu_train_batch_size`. If it happened during the evaluation phase, try reducing the `args.per_gpu_eval_batch_size`.

**Comment by ZouJoelin** [comment]
I see, I am using GTX 1080Ti with 11GB. Maybe it has something wrong with the gpu task other than the memory issue. I should check that. Thanks a lot!
