### ISSUE TITLE
About dataset download

### ISSUE THREAD

**Issue by Yanda95** [ahnjaewoo/MPCHAT#6]
I use your script to download the image based on json, but it always shows wrong status-code 429, and I cant download any one of these pictures. Could you please help me deal with it? Thank you very much

**Comment by ahnjaewoo** [comment]
Hello, thank you for reaching out and showing interest in our work!

Upon reviewing the script, it appears that downloading images from **Imgur** results in a status code 429, indicating a rate-limit error. This issue does not occur with Reddit and other pages.

As a workaround, you can exceptionally use `curl` to download the images from **Imgur**, as detailed in [this guide](https://github.com/aliparlakci/bulk-downloader-for-reddit/issues/864#issuecomment-1565190533), which I have personally tested and found to be successful for downloading images from Imgur pages.
